og_url: "http://landing.infeedl.com"
og_title: "INFEEDL: новая, более лучшая реклама"
og_description: "Мы продвигаем брендированный контент через топовые интернет-издания. С любовью к дизайну и пользователю."
