og_url: "http://landing.infeedl.com"
og_title: "INFEEDL. Расскажите свою историю"
og_description: "Платформа для продвижения брендированного контента через интернет-издания. С&nbsp;любовью к&nbsp;дизайну и&nbsp;пользователю."
