og_url: "http://www.infeedl.com"
og_title: "INFEEDL. Пришло время нативной рекламы"
og_description: "Платформа для продвижения брендированного контента через интернет-издания. С&nbsp;любовью к&nbsp;дизайну и&nbsp;пользователю."
